version: 2

sources:
  - name: erp
    tables:
      - name: production_orders
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/erp/production_orders.csv')"
      - name: part_catalog
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/erp/part_catalog.csv')"

  - name: mes
    tables:
      - name: machines
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/mes/machines.csv')"

  - name: qms
    tables:
      - name: inspection_records
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/qms/inspection_records.csv')"
      - name: scrap_events
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/qms/scrap_events.csv')"

  - name: materials
    tables:
      - name: material_lots
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/materials/material_lots.csv')"

  - name: hr
    tables:
      - name: operators
        meta:
          external_location: "read_csv_auto('/workspaces/mlops_mfg/data_source/raw/hr/operators.csv')"